name: Attach allure-report to PR

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    
jobs:

  test:
    permissions:
      # Required to upload/save artifact, otherwise you'll get
      # "Error: Resource not accessible by integration"
      contents: write
      # Required to post comment, otherwise you'll get
      # "Error: Resource not accessible by integration"
      pull-requests: write
    
    outputs:
      output-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
      comment-id: ${{ steps.find-comment.outputs.comment-id }}
      
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      continue-on-error: true
      run: docker compose -f ./docker-compose.yaml up

    - name: Extract test results
      run: |
        mkdir out
        docker cp test-allure:/app/allure-report/index.html ./out/index.html
        ls -al ./out
      if: always()
    
    - name: artifact upload
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        path: out/index.html
        if-no-files-found: error
        retention-days: 3

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
  
  attach:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - env:
          OUTPUT-URL: ${{  needs.test.outputs.output-url  }}
        run: echo "Artifact URL from previous job is $OUTPUT-URL"       

      - name: Update Comment
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          ARTIFACT-URL: ${{  needs.test.outputs.output-url  }}
          HEAD_SHA: "${{ github.event.pull_request.head.sha }}"
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{  needs.test.outputs.comment-id  }}
          edit-mode: replace
          body: |-
            ![badge]
            
            Build Successful! You can find a link to the downloadable artifact below.
            
            | Name     | Link                    |
            | -------- | ----------------------- |
            | Commit   | ${{ env.HEAD_SHA }}     |
            | Logs     | ${{ env.JOB_PATH }}     |
            | Download | ${{ env.ARTIFACT-URL }} |
