name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      continue-on-error: true
      run: docker compose -f ./docker-compose.yaml up

    - name: Extract test results
      run: |
        mkdir out
        docker cp test-allure:/app/allure-report/index.html ./out/index.html
        ls -al ./out
      if: always()

    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v4
    #   with: 
    #     personal_token: ${{ secrets.ACCESS_TOKEN }}
    #     publish_dir: ./out

    - name: github page
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out
