name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      continue-on-error: true
      run: |
        docker build . --file Dockerfile --tag test-allure:latest
        docker run test-allure:latest

    - name: Extract test results
      run: |
        ls -al .
        ls -al ./allure-reports/
      if: always()
